version: "3.8"
services:
  confluence:
    container_name: confluence
    image: ghcr.io/itdevsamurai/docker-atlassian:conf-8.6.1
    restart: unless-stopped
    volumes:
      - ./data/confluence:/var/atlassian/application-data/confluence
    environment:
      # - ATL_PROXY_PORT=443
      # - ATL_TOMCAT_SCHEME=https
      # - ATL_TOMCAT_SECURE=true
      - ATL_DB_DRIVER=org.postgresql.Driver
      - ATL_DB_TYPE=postgres72
      - ATL_JDBC_URL=jdbc:postgresql://postgres:5432/confdb
      - ATL_JDBC_USER=confdb
      - ATL_JDBC_PASSWORD=defaultdevpass
      # - JVM_MAXIMUM_MEMORY=4g
    ports:
      - 8090:8090
      - 8091:8091
    depends_on:
      postgres:
        condition: service_healthy
  postgres:
    container_name: postgres
    image: postgres:14
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=conf
      - POSTGRES_USER=conf
      - POSTGRES_PASSWORD=defaultdevpass
      - LC_COLLATE=en_US.UTF-8
      - LC_CTYPE=en_US.UTF-8
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    healthcheck:
      test: /usr/bin/pg_isready
      interval: 5s
      timeout: 10s
      retries: 10
      start_period: 3s
