name: Jira Docker Image

on:
  workflow_dispatch:
  schedule:
    - cron: "0 5 * * 0"
  push:
    paths-ignore:
      - "**.md"
      - "examples/**"
    branches:
      - main

jobs:
  generate-tags:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: "pip"
      - run: pip install -r requirements.txt

      - name: Generate tags
        id: generate-tags
        run: |
          echo "matrix=$(python scripts/generate_versions.py)" >> $GITHUB_OUTPUT
    outputs:
      matrix: ${{ steps.generate-tags.outputs.matrix }}

  publish-image:
    needs: generate-tags
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        jira-build:
          # Need full version from https://hub.docker.com/r/atlassian/jira-software/tags
          ${{ fromJson(needs.generate-tags.outputs.matrix) }}
          # - 8.20.10 # manual

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Checkout Docker Atlassian Jira
        run: git clone --recurse-submodule https://bitbucket.org/atlassian-docker/docker-atlassian-jira.git

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # - name: Login to DockerHub
      #   uses: docker/login-action@v3
      #   with:
      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}

          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Jira images
        uses: docker/build-push-action@v5
        with:
          push: true
          context: ./docker-atlassian-jira/
          file: ./docker-atlassian-jira/Dockerfile
          build-args: |
            REFRESHED_AT=$(date +%Y-%m-%d)
            JIRA_VERSION=${{ matrix.jira-build }}
          platforms: linux/amd64,linux/arm64
          tags: ghcr.io/itdevsamurai/docker-atlassian:jira-${{ matrix.jira-build }}
