name: Publish Docker Image

on:
  workflow_dispatch:
  schedule:
    - cron: "0 5 * * 0"
  push:
    branches:
      - main

jobs:
  publish-image:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        jira-build:
          - tags: latest
            platforms: linux/amd64,linux/arm64

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Checkout Docker Atlassian Jira
        run: git clone --recurse-submodule https://bitbucket.org/atlassian-docker/docker-atlassian-jira.git

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # - name: Login to DockerHub
      #   uses: docker/login-action@v2
      #   with:
      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # ======= Jira =======
      - name: Prepare Jira build
        id: jira-prepare
        run: |
          DOCKER_IMAGE=ghcr.io/itdevsamurai/docker-atlassian
          TAGZ=$(echo ${{ matrix.jira-build.tags }} | tr "," "\n")
          VERSION=${TAGZ[0]}
          for tag in $TAGZ
          do
            TAGS="${TAGS},${DOCKER_IMAGE}:${tag}"
          done
          echo ::set-output name=docker_image::${DOCKER_IMAGE}
          echo ::set-output name=version::${VERSION}
          echo ::set-output name=tags::${TAGS}

      - name: Build and push Jira images
        uses: docker/build-push-action@v3
        with:
          push: true
          context: ./docker-atlassian-jira/
          file: ./docker-atlassian-jira/Dockerfile
          build-args: |
            REFRESHED_AT=$(date +%Y-%m-%d)
            JIRA_VERSION=${{ matrix.jira-build.tags }}
          platforms: ${{ matrix.jira-build.platforms }}
          tags: ${{ steps.jira-prepare.outputs.tags }}
